In [ ]:
'''
 This program reads the American League baseball players, 2003, tsv file 
   and stores it in a list of dictionaries, one for each player
 Each line has the team, the player name, the salary and the position played.
 
 It describes the categorical fields by giving the number of categories 
      and how many examples there are of each category.
'''

import csv

infile = '/Users/kenmckee/Downloads/ALbb.salaries.2003.tsv'

def category_summarization(countrylist, fieldname):
    '''   this function takes a countrylist, 
                    which is a list of dictionaries read from the tv_life_cont.csv file
          and the name of one of the fields.
          It prints out a categorical summary for that field.
    '''   
    valuelist = []
    for player in playersList:
        valuelist.append (player[fieldname])
            
    # report the number of categories and the number of rows per category
    # the number of categories is the number of unique items, the set type gives us that
    categories = set(valuelist)
    numcategories = len(categories)

    # the number of items of each category is given by the count function
    # print these out for each category
    print('Number of categories', numcategories)
    # create a list of players in each category with their count for sorting
    categoryList = []
    for cat in categories:
        # adds a 3 tuple to the list
        categoryList.append((fieldname, cat, valuelist.count(cat)))
    # sort the categories by the field value, which is at index 2
    newlist = sorted(categoryList, key=lambda item: item[2], reverse=True)
    # print the sorted players
    for item in newlist:
        print( 'Field {:s} with Category {:s} and number {:d}'.format(item[0],item[1],item[2])) 
    # end of function definition

# create new empty list
playersList = []

with open(infile, 'rU') as csvfile:
    # the csv file reader returns a list of the csv items on each line
    ALReader = csv.reader(csvfile,  dialect='excel', delimiter='\t')

    # from each line, a list of row items, put each element in a dictionary
    #   with a key representing the data
    for line in ALReader:
      # skip lines without data
      if line[0] == '' or line[0].startswith('American') or line[0].startswith('Team')\
            or line[0].startswith('Source'):
          continue
      else:
          try:
            # create a dictionary for each player
            player = {}
            # add each piece of data under a key representing that data
            player['team'] = line[0]
            player['name'] = line[1]
            player['sal'] = line[2]
            player['position'] = line[3]
    
            # add this player to the list
            playersList.append(player)
    
          except IndexError:
            print ('Error: ', line)
csvfile.close()

print ("Read", len(playersList), "player data")

# print a few fields from all of the players read from the file

#  for player in playersList:
#    print ('Team:', player['team'], ' Player: ', player['name'], ' Salary: ', player['sal'])


# all the fields except for the 'name' field
fieldnames = ['team', 'sal', 'position']

for fieldname in fieldnames:
    category_summarization(playersList, fieldname)
    print()




In [5]:
answer = ["quit",'Quit','QUIT']
numString = []


def addup():
    numcount = 0
    
    try:
    numInput = input("Enter a number or type quit ")
    numString.append(numInput)
    numcount = float(numcount) + 1 
    while numInput not in answer:
            val = int(numInput)
        except ValueError:
            print("That's not an int!")
            continue
    else:
         

    print(numString)
    continue


addup()

SyntaxError: 'continue' not properly in loop (<ipython-input-5-f49eecc267d6>, line 20)

In [3]:
import numpy as np		# it is common to make this abbreviation
a = np.array([1, 2, 3])
a

type(a)		# python type

a.dtype		# numpy array property data type

a.shape		# numpy array property shape
(3,)			# one-dimensional (rank 1) array of length 3

#Contrast this with a two-dimensional array, where a list is given for each row in the array.

b = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
print(b)
c = np.array([[8, 4,6],[1, 2, 3]])
print(c)

[[1 2 3 4 5 6 7 8]]
[[8 4 6]
 [1 2 3]]


In [5]:
b = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
print(b)
c = np.array([[8, 4,6],[1, 2, 3]])
print(c)

[[1 2 3 4 5 6 7 8]]
[[8 4 6]
 [1 2 3]]


In [19]:
import numpy as np
list = (1, 2, 3, 4, 5, 6, 7, 8)
firstArray = []
secondArray = []
	
for i in list:
	if i <= 4:
		firstArray.append(i)
	else:
		secondArray.append(i)
		

lol = secondArray.append(firstArray)
print(secondArray)
print(firstArray)
print(lol)
t = np.array(firstArray)
t = np.append(t, secondArray)

[5, 6, 7, 8, [1, 2, 3, 4]]
[1, 2, 3, 4]
None


ValueError: setting an array element with a sequence.

In [28]:
y = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
print(x)

print([sum(x) for x in zip(*y)])

z = [sum([i[b] for i in y]) for b in range(len(y[0]))]

print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[34, 38, 42, 46, 50]
[34, 38, 42, 46, 50]


In [12]:
b.shape		# two-dimensional array with two rows and three columns
(2, 3)



#For two-dimensional arrays, we use just one square bracket and separate the index numbers by a comma.

b[1,2]

b[1,2] = 7
b




array([[1, 2, 3],
       [4, 5, 7]])

In [21]:
#We use indexing with square brackets, giving an index number from 0 to the length of the dimension—1.  The same indexing conventions apply as in Python, e.g., you can use -1 to get the last element.

a[0]

a[0] = 5		# assign a new value to the first location in a
a

array([5, 2, 3])

In [15]:
#The numPy package hasa number of functions to help createarrays with basic shapesand values.

t = np.zeros((2,2))	#array ofall zeroes
t

array([[0., 0.],
       [0., 0.]])

In [16]:
t = np.ones((1,2))		#array ofall ones
t

array([[1., 1.]])

In [17]:
t = np.full((2,4), 7)  	#array of constants (in this case,all 7s)
				# thisalso puts outa future warning
t

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [13]:

t = np.random.random((2,2))	#array of random numbers
t

t.dtype

dtype('float64')

In [18]:
t = np.eye(2)		# identity matrix
t


array([[1., 0.],
       [0., 1.]])

In [14]:
#And one final function uses the NumPy function “arange()”, which is analogous to the Python function “range()” to generate a sequence of numbers.

c = np.arange(10)
c


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])